#!/bin/bash

shell=$(ps -o command $$ | tail -n 1 | awk '{print $0}' | awk -F '/' '{print $NF}')
if [[ ${shell} == zsh ]]
then
    SCRIPT_DIR=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)/$(basename -- "$0")" | sed 's/\/mdscode//g')
else
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
fi

declare -g SRC_DIR=${SCRIPT_DIR}/src
source ${SRC_DIR}/main_flow.sh

# We can only return from a function or sourced script
declare -g IS_SOURCED
(return 0 2> /dev/null) && IS_SOURCED=YES || IS_SOURCED=NO

if [[ ${IS_SOURCED} == NO ]]
then
    start "${@}"
fi

